### ISSUE TITLE
thecocktaildb lookup fails

### ISSUE THREAD

**Issue by mk6032** [forslund/skill-cocktail#12]
I reported this in the skills chat room of chat.mycroft.ai ..

mkeys
11:00 AM
Hello, I'm testing the "cocktails" skill and asked "How do I mix a manhattan" but this fails. If I go to https://thecocktaildb.com/drink.php?c=11008-Manhattan it exists, so I assume there's something missing from the skills settings.json. I can't find any documentation on it

eltocino
11:02 AM
what's in the logs? (/var/log/mycroft/)

mkeys
11:02 AM
additionally if I ask it one of the predefined questions like "how do i mix a moscow mule" that works

@eltocino pasting error below

2020-03-26 10:46:04.646 | ERROR    | 19152 | mycroft.skills.mycroft_skill.mycroft_skill:on_error:799 | An error occurred while processing a request in Cocktail Skill
Traceback (most recent call last):
  File "/home/matt/mycroft-core/mycroft/skills/mycroft_skill/event_container.py", line 66, in wrapper
    handler(message)
  File "/opt/mycroft/skills/cocktails.forslund/init.py", line 54, in get_recipie
    'ingredients': ', '.join(ingredients(cocktail)[:-1]),
  File "/opt/mycroft/skills/cocktails.forslund/init.py", line 28, in ingredients
    drink['strIngredient' + str(i)])))
TypeError: sequence item 0: expected str instance, NoneType found

before that ..

11:06 AM
2020-03-26 10:44:31.071 | INFO     | 19152 | QuestionsAnswersSkill | Searching for how do i mix a manhattan
Removing event fallback-query.mycroftai:QuestionQueryTimeout
Removing event fallback-query.mycroftai:QuestionQueryTimeout
Removing event fallback-query.mycroftai:QuestionQueryTimeout
Removing event fallback-query.mycroftai:QuestionQueryTimeout
2020-03-26 10:44:33.526 | INFO     | 19152 | QuestionsAnswersSkill | Timeout occured check responses

thelastproject
11:17 AM
That's definitely, without a doubt, a bug in the skill

I'd say make an issue on the GitHub for that skill if it doesn't already exist

**Comment by forslund** [comment]
Thanks for reporting, that's definitely a bug. I'll see if I can reproduce the issue here.

**Comment by forslund** [comment]
I can't quite get it to fail here, let me see if we can deduce something from the error logs...Are you sure Mycroft heard Manhattan?
